### ISSUE TITLE
Ambiguous condition with , in core.fr

### ISSUE THREAD

**Issue by jamesbowman** [gerryjackson/forth2012-test-suite#18]
Looking at this sequence:

https://github.com/gerryjackson/forth2012-test-suite/blob/master/src/core.fr#L548-L556

then there is no guarantee that the data-space pointer will be aligned when executing `,`. Many Forths implemement `CONSTANT` using `CREATE` which would hide this issue.

http://forth.sourceforge.net/std/dpans/dpans6.htm#6.1.0150

```
"... An ambiguous condition exists if the data-space pointer is not aligned prior to execution of ,."
```

**Comment by gerryjackson** [comment]
You're correct and well spotted. Its only been in core.fr for over 20 years!

We have to make sure that dataspace is aligned before testing , and since CREATE isn't tested until later we should test ALIGN and ALIGNED first.

I see that CONSTANT isn't tested until later (line 735) but is well used before, as early as line 40. I should probably add CONSTANT to the words given a simple test in prelim.fth.

Also I see that there is a comment that negative ALLOT needs to be tested. We might as well add that while we're about it.

I'll think about it later when I've a bit more time.

**Comment by gerryjackson** [comment]
Sorry, I forgot about this issue until I updated something else. I have added a test for ALIGN and ALIGNED and used ALIGN just before the test for , (comma).

As CONSTANT is used quite often in core.fr before being tested I have added a simple test for CONSTANT in prelimtest.fth
