### ISSUE TITLE
gforth 0.7.3 fails with coreexttest.fth:400: Undefined word BUFFER

### ISSUE THREAD

**Issue by lucabol** [gerryjackson/forth2012-test-suite#30]
Hi, forth beginner here. Apologies if it is already known. I tried to figure it out myself, but I still need to learn too much about forth. Full error below.

gforth 0.7.3 (Ubuntu default) on 
Ubuntu 20.04.3 LTS on Windows 10 x86_64
Kernel: 5.10.60.1-microsoft-standard-WSL2

Test utilities loaded
***********redefined MA1  **
in file included from runtests.fth:17
coreexttest.fth:400: Undefined word
T{ 8 >>>BUFFER:<<< BUF:TEST -> }T
Backtrace:
$7FC104751A68 throw
$7FC104767DD0 no.extensions
$7FC104751D28 interpreter-notfound1

**Comment by gerryjackson** [comment]
It fails because gforth 0.7.3 doesn't include the word BUFFER: that is defined in Forth 2012. gforth 0.7.3 is years old and probably predates Forth 2012. The same problem will occur with most, if not all words added in Forth 2012. STandard definitions of BUFFER: and other Forth 2012 words can be found in the standard which is at https://forth-standard.org/standard/words 

Either use those definitions or download a snapshot version of gforth 0.7.9 from https://www.complang.tuwien.ac.at/forth/gforth/Snapshots/ but you may have to compile it yourself. Alternatively comment out the failing tests.

I did reply several days ago to lucabol via Github and am surprised the reply didn't appear here.

**Comment by ruv** [comment]
@lucabol, see also a related Issue #23 — a feature to automatically skip the tests for absent words is wanted.

**Comment by lucabol** [comment]
Yep, compiled the newest version, and everything works. I wrongly assumed gforth in Ubuntu was somehow recent.

**Comment by gerryjackson** [comment]
That's a natural assumption to make, I don't know why they don't release a new version  more often.

Thanks for letting me know
